const FETCH_DEPLOYMENTS_REQUEST = 'FETCH_DEPLOYMENTS_REQUEST';
const FETCH_DEPLOYMENTS_SUCCESS = 'FETCH_DEPLOYMENTS_SUCCESS';

const FETCH_DEPLOYMENT_REQUEST = 'FETCH_DEPLOYMENT_REQUEST';
const FETCH_DEPLOYMENT_SUCCESS = 'FETCH_DEPLOYMENT_SUCCESS';

const RUN_DEPLOYMENT_REQUEST = 'RUN_DEPLOYMENT_REQUEST';
const RUN_DEPLOYMENT_SUCCESS = 'RUN_DEPLOYMENT_SUCCESS';

const DELETE_DEPLOYMENT_REQUEST = 'DELETE_DEPLOYMENT_REQUEST';
const DELETE_DEPLOYMENT_SUCCESS = 'DELETE_DEPLOYMENT_SUCCESS';

const STOP_DEPLOYMENT_REQUEST = 'STOP_DEPLOYMENT_REQUEST';
const STOP_DEPLOYMENT_SUCCESS = 'STOP_DEPLOYMENT_SUCCESS';

const CREATE_DEPLOYMENT_REQUEST = 'CREATE_DEPLOYMENT_REQUEST';
const CREATE_DEPLOYMENT_SUCCESS = 'CREATE_DEPLOYMENT_SUCCESS';

export {
  FETCH_DEPLOYMENTS_REQUEST,
  FETCH_DEPLOYMENTS_SUCCESS,
  FETCH_DEPLOYMENT_REQUEST,
  FETCH_DEPLOYMENT_SUCCESS,
  RUN_DEPLOYMENT_REQUEST,
  RUN_DEPLOYMENT_SUCCESS,
  DELETE_DEPLOYMENT_REQUEST,
  DELETE_DEPLOYMENT_SUCCESS,
  CREATE_DEPLOYMENT_REQUEST,
  CREATE_DEPLOYMENT_SUCCESS,
  STOP_DEPLOYMENT_REQUEST,
  STOP_DEPLOYMENT_SUCCESS
};
