const SET_IS_LOADING = 'SET_IS_LOADING';
const SET_IS_ERROR = 'SET_IS_ERROR';

const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT';
const SET_CURRENT_EXPERIMENT = 'SET_CURRENT_EXPERIMENT';

export {
  SET_CURRENT_EXPERIMENT,
  SET_CURRENT_PROJECT,
  SET_IS_ERROR,
  SET_IS_LOADING
};
