const FETCH_MODELS_REQUEST = 'FETCH_MODELS_REQUEST';
const FETCH_MODELS_SUCCESS = 'FETCH_MODELS_SUCCESS';

const FETCH_MODEL_REQUEST = 'FETCH_MODEL_REQUEST';
const FETCH_MODEL_SUCCESS = 'FETCH_MODEL_SUCCESS';

const DELETE_MODEL_REQUEST = 'DELETE_MODEL_REQUEST';
const DELETE_MODEL_SUCCESS = 'DELETE_MODEL_SUCCESS';

const CREATE_MODEL_REQUEST = 'CREATE_MODEL_REQUEST';
const CREATE_MODEL_SUCCESS = 'CREATE_MODEL_SUCCESS';

export {
  FETCH_MODELS_REQUEST,
  FETCH_MODELS_SUCCESS,
  FETCH_MODEL_REQUEST,
  FETCH_MODEL_SUCCESS,
  DELETE_MODEL_REQUEST,
  DELETE_MODEL_SUCCESS,
  CREATE_MODEL_REQUEST,
  CREATE_MODEL_SUCCESS
};
