const FETCH_MODEL_VERSIONS_REQUEST = 'FETCH_MODEL_VERSIONS_REQUEST';
const FETCH_MODEL_VERSIONS_SUCCESS = 'FETCH_MODEL_VERSIONS_SUCCESS';

const FETCH_MODEL_VERSION_REQUEST = 'FETCH_MODEL_VERSION_REQUEST';
const FETCH_MODEL_VERSION_SUCCESS = 'FETCH_MODEL_VERSION_SUCCESS';

export {
  FETCH_MODEL_VERSIONS_REQUEST,
  FETCH_MODEL_VERSIONS_SUCCESS,
  FETCH_MODEL_VERSION_REQUEST,
  FETCH_MODEL_VERSION_SUCCESS,
};
