const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';

const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';

const EDIT_PROJECT_REQUEST = 'EDIT_PROJECT_REQUEST';
const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';

const RUN_PROJECT_REQUEST = 'RUN_PROJECT_REQUEST';
const RUN_PROJECT_SUCCESS = 'RUN_PROJECT_SUCCESS';

const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';

const RESTORE_PROJECT_REQUEST = 'RESTORE_PROJECT_REQUEST';
const RESTORE_PROJECT_SUCCESS = 'RESTORE_PROJECT_SUCCESS';

const TERMINATE_PROJECT_REQUEST = 'TERMINATE_PROJECT_REQUEST';
const TERMINATE_PROJECT_SUCCESS = 'TERMINATE_PROJECT_SUCCESS';

const ARCHIVE_PROJECT_REQUEST = 'ARCHIVE_PROJECT_REQUEST';
const ARCHIVE_PROJECT_SUCCESS = 'ARCHIVE_PROJECT_SUCCESS';

const CREATE_PROJECT_REQUEST = 'CREATE_PROJECT_REQUEST';
const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';

export {
  FETCH_PROJECTS_REQUEST,
  FETCH_PROJECTS_SUCCESS,
  FETCH_PROJECT_REQUEST,
  FETCH_PROJECT_SUCCESS,
  EDIT_PROJECT_REQUEST,
  EDIT_PROJECT_SUCCESS,
  RESTORE_PROJECT_REQUEST,
  RESTORE_PROJECT_SUCCESS,
  RUN_PROJECT_REQUEST,
  RUN_PROJECT_SUCCESS,
  ARCHIVE_PROJECT_REQUEST,
  ARCHIVE_PROJECT_SUCCESS,
  DELETE_PROJECT_REQUEST,
  DELETE_PROJECT_SUCCESS,
  TERMINATE_PROJECT_REQUEST,
  TERMINATE_PROJECT_SUCCESS,
  CREATE_PROJECT_REQUEST,
  CREATE_PROJECT_SUCCESS
};
