const FETCH_RUNS_REQUEST = 'FETCH_RUNS_REQUEST';
const FETCH_RUNS_SUCCESS = 'FETCH_RUNS_SUCCESS';

const FETCH_RUN_REQUEST = 'FETCH_RUN_REQUEST';
const FETCH_RUN_SUCCESS = 'FETCH_RUN_SUCCESS';

const DELETE_RUN_REQUEST = 'DELETE_RUN_REQUEST';
const DELETE_RUN_SUCCESS = 'DELETE_RUN_SUCCESS';

export {
  FETCH_RUNS_REQUEST,
  FETCH_RUNS_SUCCESS,
  FETCH_RUN_REQUEST,
  FETCH_RUN_SUCCESS,
  DELETE_RUN_REQUEST,
  DELETE_RUN_SUCCESS
};
